---
languages:
  PHP: true
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phan:
    enabled: true
    config:
      file_extensions: "php"
ratings:
  paths:
  - "**.php"
  - "**.md"
exclude_paths:
- spec/
