language: php

sudo: false

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run -v --no-interaction
  - vendor/bin/phpcs
  - vendor/bin/test-reporter
